name: Documentation
on: 
    push: 
        branches:
            - master    
jobs: 
    docs:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4
              with:
                node-version: 12
            - name: Set Git parameters
              run: |
                git config --global user.name Kovacs Alex
                git config --global user.email 31011461+alexthemaster@users.noreply.github.com
            - name: Install dependencies
              run: npm ci
            - name: Clone the gh-pages branch
              run: |
                mkdir gh-pages
                cd gh-pages
                git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/alexthemaster/filelist.js.git .
                git checkout gh-pages
            - name: Install JSDoc
              run: npm install --global jsdoc
            - name: Build the docs
              run: jsdoc src/index.js -t ./node_modules/minami -R README.md -d ./docs
            - name: Add files to git and commit them
              run: |
                rsync -r ./docs/. ./gh-pages 
                cd gh-pages
                git add .
                git commit -m "docs: ${{ github.sha }}" || true
            - name: Push files to GitHub
              run: |
                cd gh-pages
                git push origin gh-pages || true